### ISSUE TITLE
vmImage.project : Client says `project/foo`, API however expects `foo`

### ISSUE THREAD

**Issue by s4shyam95** [googleapis/python-notebooks#155]
Incorrect comment [here in the client](https://github.com/googleapis/python-notebooks/blob/main/google/cloud/notebooks_v1/types/environment.py#L120)

The VMImage class has a comment saying it expects the project attribute to be of format `project/foo`.
However, that results in an error with an error from the API containing `project/project/foo`.
Using only `foo` in the client results in the request succeeding.
This might not be the appropriate channel as the comment could be sourced from the api proto defintions by the gapic generator,
If so please let me know the appropriate repository.

**Comment by nayaknishant** [comment]
Hi @s4shyam95 could you provide some more context? What is the error you're receiving? Is the error occurring because `project/foo` is not a valid name? I'm thinking a potential fix is removing the line `Format: projects/{project_id}`. I can (or if you would like to) open a bug here: https://github.com/googleapis/gapic-generator-python/issues/new/choose to remove the comment.

**Comment by s4shyam95** [comment]
It's just a bad comment, in the client, the vmImage project is actually to be entered only as `{project_id}` and not `project/{project_id}`. This is likely sourced from the proto since the client is genrated, we should fix the docstring in the proto file where this originate.

**Comment by parthea** [comment]
I reviewed this issue and agree with @s4shyam95 that the source proto needs to be updated. 
https://github.com/googleapis/googleapis/blob/master/google/cloud/notebooks/v1/environment.proto#L72. I've filed b/231030718 for the API team to take a look.

**Comment by parthea** [comment]
Googlers see cl/445770030
